version: "3.9"

volumes:
  node_modules_volume:

services:
  nextjs:
    build: ./
    volumes:
      - ./src:/opt/app
      - node_modules_volume:/opt/app/node_modules
    ports:
      - '31000:3000'
    command: bash -c "npm install && npm run dev"
    environment:
     - WATCHPACK_POLLING=true

