name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.13.1
        uses: actions/setup-node@v1
        with:
          node-version: "14.13.1"
      - run: yarn install
      - run: yarn run test
