name: Test

on: push

jobs:
  jest-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: npm install
        working-directory: ./src
        run: npm ci

      - name: Run Jest
        run: npm run test -- --ci
