name: Test

on: push

defaults:
  run:
    working-directory: src

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: npm install
        run: npm insta

      - name: Run Jest
        run: yarn jest
